### ISSUE TITLE
Bug when using elements in the climatic_summary function

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/cdms.products#67]
@dannyparsons I'm getting an error when running the `climatic_summary` function, coming from this line:

https://github.com/IDEMSInternational/cdms.products/blob/b0ecc5d02c5dc3fb765684b35c2ea1404d312259/R/climatic_summary.R#L216

I'm not sure how to fix it. It seems to occur if I put an element in the `elements` parameter.

```
climatic_summary(data = daily_niger, date_time = "date", station = "station_name",
                              elements = c("rain", "tmax"))
```

**Comment by dannyparsons** [comment]
Thanks for spotting this. The bug was only when using the default summary `dplyr::n` where the code was trying to add the `.x` parameter into it (which is usually what you want for min, max etc.). 

So it was trying to run `dplyr::n(x)` which gives an error.
I've fixed this by allowing the summary to also be a formula e.g. `~dplyr::n()` where it won't add anything else to the function call.

**Comment by dannyparsons** [comment]
We should add a test for this so that we can spot if this ever fails again.
